### ISSUE TITLE
Missing image path for AvaEdgeGatewayModule in sample deployment manifests

### ISSUE THREAD

**Issue by leeprtc** [iot-for-all/iotc-ava-gateway#10]
In the sample deployment manifests under setup/deploymentManifests, for both deployment.openvino.amd64.json and deployment.quickstart.amd64.json, no container image was specified for AvaEdgeGatewayModule. Instead I see the following.

                "AvaEdgeGatewayModule": {
                        "settings": {
                            "image": "<MCR_PATH>",
                            "createOptions": "{\"ExposedPorts\":{\"9229/tcp\":{}},\"HostConfig\":{\"PortBindings\":{\"9229/tcp\":[{\"HostPort\":\"9229\"}]},\"Binds\":[\"/var/iotcentralgw/storage:/data/storage/\",\"/var/iotcentralgw/media:/data/media/\"]}}"
                        },

As there is a <MCR_PATH> for the image value, is there a missing reference to an image in Microsoft Container Registry?

**Comment by sseiber** [comment]
Hi @leeprtc - Sorry for the confusion - there is an assumption that the developer would use this repository and build from the module from the source. If you push the built container to a custom container registry you would also need to supply those credentials at the top of the deployment manifest.

If you just want to experiment with a pre-built module you can use this one:
sseiber/ava-edge-gateway:4.0.1-amd64-debug

Sorry for the confusion the README doesn't explicitly state that.
