### ISSUE TITLE
Build IoTC AVA Gateway on arm device

### ISSUE THREAD

**Issue by HieuPhan33** [iot-for-all/iotc-ava-gateway#9]
Hi,

Thanks for the code. It works like a charm on the PC - amd64 architecture.

However, it doesn't work when I build IoTC AVA Gateway on a Jetson Nano - arm64-v8 architecture.
Due to the platform mismatch (building an _amd64_ docker image on an _arm_ machine), the device couldn't deploy two modules, i.e., AvaEdgeGatewayModule and OnvifModule.
<img width="856" alt="image" src="https://user-images.githubusercontent.com/32691090/161381749-e877e1dd-dde6-450b-a2ea-6237f56ec842.png">

Here's the error: 
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error]
```

Could you please guide me how to deploy these two images on the arm device?

The working environment is described as below.
OS: Ubuntu 18.04.
Device: NVIDIA Jetson Nano 4GB.
Architure: arm64/v8.

Many thanks.

**Comment by HieuPhan33** [comment]
Hi, just a quick update.

I found the dockerfile: `docker/arm64-v8-debug.Dockerfile` in the repository.
I think that it is the dockerfile for AvaEdgeGatewayModule. Please correct me if I'm wrong.

I just use it to build the arm docker for AvaEdgeGatewayModule. Now I can see that the AvaEdgeGatewayModule is running:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/32691090/161383296-fa4efb09-a051-48be-86ed-b206875c1d63.png">

Now the only problem left is the OnvifModule. Please help me re-build the OnvifModule docker image for arm architecture.
Appreciate your help.

Thanks!

**Comment by sseiber** [comment]
Hi @HieuPhan33 - unfortunately the OnvifModule is not open source at this time so it is not possible for you to build your own image. And, looking at the manifests it is not built to be a multi-platform image. You don't specifically need to deploy the OnvifModule unless you are specifically going to use the Onvif features of a camera. If you only need to process video via an RTSP stream you can configure your camera in IoT Central using the "Plain Camera Settings" as shown in this section in the README.
https://github.com/iot-for-all/iotc-ava-gateway#create-a-camera-device

**Comment by HieuPhan33** [comment]
Hi, @sseiber 
I have followed the tutorial, set Onvif camera to False, and successfully provisioned the camera. But I get errors at the "Start AVA processing" step. Here are the details:

Create non-Onvif camera:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/32691090/161857355-05416de1-acc9-4a50-b6fb-52126a07b383.png">

The camera is provisioned but template is "Unassigned":
<img width="852" alt="image" src="https://user-images.githubusercontent.com/32691090/161857753-a2a31232-3067-4d29-bf38-6c0db3f17726.png">

Now we assign AvaOnvifCameraDevice template:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/32691090/161857907-deb915d6-36d2-4ef8-887a-b4ad35f7fe25.png">

Okay, camera-002 has been successfully provisioned just like what the document describes:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/32691090/161858191-bbb0c1db-71ef-4717-b9e0-5e94aab16f7f.png">

Now, I start AVA processing pipeline on camera-002:
<img width="684" alt="image" src="https://user-images.githubusercontent.com/32691090/161858528-bc4deeba-a6fd-4768-9072-adebc241b7e5.png">

Here are the error logs from the IoT Edge device:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/32691090/161858943-d25d4111-4f5e-4019-83d8-4e3b50e09b6f.png">

<img width="742" alt="image" src="https://user-images.githubusercontent.com/32691090/161859049-d0d1a60f-f6bf-4ddb-92d4-03df53b6bfad.png"> ... then error 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/32691090/161859229-542af575-f466-4561-82c9-21a3c3517c58.png">

From my understanding, it tries to invoke OnvifModule method to first clear existing pipelines (_livePipelineDeactive, pipelineTopologySet_), create pipeline (_pipelineTopologySet_).

_But it couldn't find OnvifModule method_. Could you please confirm if OnvifModule is not needed for starting AVA processing?

Thanks

**Comment by sseiber** [comment]
Hi @HieuPhan33 - I would suggest turning on the debug telemetry option on the module (on the "Manage" tab for the device in IoT Central). This will give you more verbose logging on what is attempting to be called and what is failing.

You can also deploy a debug version of the module and put a breakpoint on the iotCentralModule where it it calling invokeMethod. https://code.visualstudio.com/docs/remote/containers

The methods for livePipelineDeactivate and pipelineTopologySet are on the AVA module not the OnvifModule.

**Comment by HieuPhan33** [comment]
I have turned on both debug options:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/32691090/161862901-9d1947e5-ecdd-4029-9d49-4d9eda386497.png">

Here are more verbose errors:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/32691090/161863445-480cda93-be66-4cab-8a8f-8009ff09fb3b.png">

The error message is still not very clear to me why it couldn't find invokeMethod. 
Could you please elaborate more on how to deploy a debug version of the module (I guess you mean AvaEdgeGatewatModule)?

**Comment by HieuPhan33** [comment]
Hi @sseiber,
I tried to run AvaEdgeGateway on a normal PC (amd64 architecture) without OnvifModule. It does work.
I compare the deployment manifest between AVA Edge Gateway - amd device template (which is working) and AVA Edge Gateway arm device template (which is not working).

They are the same, except the docker image for AvaEdgeGatewayModule: "sseiber/ava-edge-gateway:4.0.1-amd64-debug" versus "stevephan46/ava-edge-gateway-arm64v8-debug" - my deployed arm image.

Hence, the problem is because of the docker image. Indeed we can run AVA pipeline without OnvifModule.

Now let's discuss the docker image issue.
I deploy the image using this `docker/arm64-v8-debug.Dockerfile` from your repository.
Is there any way that we can know what is wrong with this docker image? That makes it unable invokeMethod?
